spring:
  config.activate.on-profile: default
  datasource:
    url: jdbc:mysql://localhost:3306/SittingSeat?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: password!23
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: localhost
    port: 6379
    # password: password!23

jwt:
  secretKey: 5f929e80d1a736e32ac586b80416d187ab46541995306a70c1c7f83bdc3609ec3477a921e6f7c330663d7b528b15c29c0b9ae191135e0de11fd11fa7e5388d60

time:
  ms:
    minute: 60000
    hour: 3600000
    day: 86400000
  token:
    accessExp: 86400000
    refreshExp: 2592000000