spring:
  config.activate.on-profile: default
  datasource:
    url: jdbc:mysql://sittingseat-db.czymyzxo0gbq.ap-northeast-2.rds.amazonaws.com:3306/SittingSeat?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: password!23
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 64872dab9d85f74133c5a48e98cd29e3
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
              - gender
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  redis:
    host: localhost
    port: 6379
    # password: password!23

    # Naver smtp server 사용
  mail:
    host: smtp.naver.com #smtp 서버 주소
    id: suudh99
    port: 465 # 메일 인증서버 포트
    username: suudh99@naver.com
    password: dlehdgus12~ #네이버 비밀번호
    email: suudh99@naver.com
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          #            required: true
          auth: true
          #          connectiontimeout: 5000
          #          timeout: 5000
          #          writetimeout: 5000
          ssl:
            #trust: smtp.naver.com
            enable: true #반드시 필요 -> SSL 필요로 되어있으면
cloud:
  aws:
    s3:
      bucket: sittingseat
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: AKIAXW4DDD5LZRII4EWE
      secretKey: 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

jwt:
  secretKey: 5f929e80d1a736e32ac586b80416d187ab46541995306a70c1c7f83bdc3609ec3477a921e6f7c330663d7b528b15c29c0b9ae191135e0de11fd11fa7e5388d60


time:
  ms:
    minute: 60000
    hour: 3600000
    day: 86400000
  token:
    accessExp: 86400000
    refreshExp: 2592000000